language: node_js
node_js:
- 14
os: ubuntu
branches:
  only:
  - master
before_install:
- pwd
script:
- npm install
- npm test
env:
  global:
    secure: k20ipAEEz/GgaotosGN3hBozjYy+arbhUjRlUcJNVnlgqHkkkY+OAEJIQLdyzBX0D5Fr1mrjopZDIlcd+fv3I3mX2eJ16TiFDghgYnyYiDHA8iCFd9xqhybfTCK7lSRF3G8+m2gWDcx6X77cLWabJ7PCOO5V82F/gLbZqq/WTiD3BR7JPNaRxaLmGa6FGUgQYdxlKHtZoa3ABY4xUDOeWg5Rx9BCOuCoPoKDyt6ZWTRn0EHMpxPwi0Soc/wUOK4Zf6K8ObCOQALmJOE0QAR4wasD8min8r+lSV1BtfWQU5Zz6alBfL0r62gUx3ITbbtL0OllZgVLnLjtzuLR+CCtZZ4kGi5C2ku8R+hwHt5WaKDv+PD4jEy4AYAAVAUk9z0fLtOUVSpad64MPINdEmlgnNLDGaO549hY4cwMr9kOWH/h7siqO4NV/OcmCqymgIcw7IYz2Uy8iTN94jte+0rijcpL+d5Q3cDBcGmlLk6B0FfQ/7kvbUXnRdEyQdVifiTby7u2BK33p3GvZZXIx9KwlvooEEJOh2LiUVecaKsmK2La1+1vELw/2PSZDkT9i6gV3DICvjc1kzkHZAVyBEEK8LcleKciAYhslf8wHtUGDr5LZau7qHwwtFb+l6XlTZdTSVuMoOTIzqHG8sghCv40Cf6cKE+qrEo6lZoULs9Ddzo=
