language: node_js
node_js:
- 14
os: ubuntu
branches:
  only:
  - master
before_install:
- pwd
script:
- npm install
- npm test
env:
  secure: ooBinOruO8yhucwMt8ggAyRp43gocatNKjZatcbSGNDQfIyFQy7YjoJsW4r7gpYOQ3IAunQhormN4ZwXIERJsz/GUc/uDVIuP+O9gr1XzIVWow3E86xoHgefIntId4Mq3bIeC3mM+QMQ1KrYBs9zlFzKVN+36UV6HKBsNoBOJ6jJWS8V0zauHblp0yrDoOqOVF1SZhau/kG4+j4xyM2B4EbV6jbSampKcfmSuKBgK0ySNzdCjd9YF43IQSKikPHraPeL/WHraTA+LFoaQXpMCw2IVsTaT6//rLSMzGppBL8tYKZ2Oa+iGI3zSKetZlEMV/JxDeEgMIHjFil2R7A8+Kq11Y0L7AZ7TvvsCNlK6+fp4j20zeELH2u9oLWjxL/F4+W95evNFEmXuApeKjPRY1kLxUKj8BzzggseOZ7dfvKHv3BzzaYS3K+KjmH3a/NI9kiUzpRyMf0TOXYTFjikeTXMhfwuP+uGhAAzTgIWhaUOjkTuxMIk14dTzMy0O8eOnBGmsDgid+MzXN29aCHgZ4IvM2/hDLz8aK6htigCRLL6UxIoJvMR4qmDCBWnIGZ9aj1+gyLlcWlyXJIzjPK1rRq/vvols55picztDgl7ZTe4vJEsL03WhDTOjP1vKtrf6Dde/EJSXOCv2m1Z58qf/ZC9eLKdi+7PXi/iM57815c=
