language: node_js
node_js:
- 14
os: ubuntu
branches:
  only:
  - master
before_install:
- pwd
- echo $TRAVIS_MESSAGE
script:
- npm install
- npm test
env:
    secure: nisBOpo/n05BEoRixb3pXLdPJDtQk70OAAt/5e25EbPMeloob+Rwb587A55UoKlD1PIBm+E/JS4xlL1/rAmQygcpPEDDKV/i0f4W/w7eLnWXCTkNbVCc3pjf8VxdnB2LwCoq/yLfTbJE9VVZ7ScTaEkAich5BhQ2h/JxtEaK65ZvNYJIxlgSmIfg9xe8NSL2Z7WfxTJNENlPJgS2lk9rQQNaR5eQrICMptG0XceGz+YnaCMTGQ9NDHuNSjWSmEpP+V5wit6qvUhS6zTp9J9lRBwovpEMijRgJDtemZR73xo8gGr5o88TN019m2yuIvl0Pap2jDJddTH8EYrnL9o8Zge6g4AhuQT8007oj3D71gAv0+utuoBIi2wlUhkN2TFY9Q9fTOOaVA+NZeY+zzUn7uuQmrfl3RTWYUO7PhKCBUxybeC34cnrw6EklwTdhQg9dFhfie3n00luxT+zEYohFxHUF8100TH0Or4G08t0nhhPYzO1jmW6gufguTJzAYUZ4oGTIqmagYgv0mzmOfr2ASTkkUwtNOMFOCLUeVadk4R3ttU+qWTwMTlYmkjrEkSCUrDQeLDMaJnmh4gHR/GjgCQXmeUDHQwRU97XldDV4WU0v+fWRKlGDHG3uObkqbLq731CAUBjinyhLHV0VCUfxrfGtmTZWQSphtc0LpFzIDE=
