language: node_js
node_js:
- 14
os: ubuntu
branches:
  only:
  - master
before_install:
- pwd
- echo $TRAVIS_MESSAGE
script:
- npm install
- npm test
env:
  global:
    - TRAVIS_MESSAGE ="All Good Things Take Time"