language: node_js
node_js:
- 14
os: ubuntu
branches:
  only:
  - master
before_install:
- pwd
script:
- npm install
- npm test
env:
  global:
    secure: DK0HPbDvyTfhRbynNQKcPPyPloB/2y7qKCvbT+p3r4+67hij0plAksDzmmSIFrAtYmAK2hFXN5gHvCsUZggygqwN4u770q8boFe2vNWSKXt224ROVUN2kVqQ0Sy/C2QUL3JGqSE0AZ6ddcXeLLppKfQUaAmz51Tb1j87vnypnZc+K60Ra3KN2O0qs5YgLJED5Xg7hxFAzK234Vh0VSBR7C1sizyBfOzbheq7gWq4uNyiDl0VYivvtG0DMsJzovmJqaaY7qTNniq9y1JYq6wIyymW+SQGPIGgnfRIDD/qYFbRoGUMBCXOPjIL2ydQ6FZKvBcsudt2qUD37uA4RxHHV25xRZdMR7FS9gznJdYea2FITws4q77A7BKG8SSFWrCLtHXUub613YrSA0xF688Vu0GFjDbUk0/yImBqooS5R1Mb0mXF2aMzXZ+qi83dP4CrhA6ES1G/fQy5DTtuS/j0DFp1174G+H62hskpKPelR5PFzsnfUt5i4F5JjlBUaBtP2FCXfO1QsYaTrDkbh1mUiZOwF1JX1JQWc2lxWPbtfwluT4rWAlsao8/kuiqf42GWVe7FspupE2ivgGh/93/bUdVGqTPA/pP2ml65LrfPkv/i/qQAG+ZtMf7zONWlnkjxHflhCiL+1/VeLY1U1HYxg2gkj7eJ1NZ46C0eMJ6T1+M=
